spring:
  profiles:
    active: dev
  application:
    name: zuul-server
server:
  port: 6065
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6060/eureka/
zuul:
  routes:
    goods:
      path: /goodsservice/**
      serviceId: goods-service
    order:
      path: /orderservice/**
      serviceId: order-service