server:
  port: 6061
spring:
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: jiangdou.xyz:9300
      repositories:
        enabled: true
  redis:
    database: 1
    host: 119.29.18.116
    password: Hsb201911
    jedis:
      pool:
        max-active: 1024
        max-idle: 200
        max-wait: 10000
        min-idle: 0
    port: 6338
    timeout: 10000
  profiles:
    active: ${spring.cloud.config.profile}
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: goods-service
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.test.common.entity
  configuration:
    cache-enabled: false
    local-cache-scope: statement
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6060/eureka/
test:
  name: tom
  num: 20
#  instance:
#    instance-id: ${spring.cloud.client.hostname}:${spring.cloud.client.ipAddress}:${server.port}
#    prefer-ip-address: true
