spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-service
  profiles:
    active: ${spring.cloud.config.profile}
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.0.193
    port: 5672
  cloud:
    bus:
      enabled: true #是否启用springcloud config bus
      trace:
        enabled: true # 开启跟踪总线事件
management:
  endpoints:
    web:
      exposure:
        include: refresh
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.test.common.entity
  configuration:
    cache-enabled: false
    local-cache-scope: statement
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6060/eureka/
server:
  port: 6063
test:
  name: tom7
