spring:
  profiles:
    active: ${spring.cloud.config.profile}
  application:
    name: zuul-server
server:
  port: 6065
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6060/eureka/
zuul:
  routes:
    goods:
      path: /sgoods/**
      serviceId: goods-service
    order:
      path: /sorder/**
      serviceId: order-service
    user:
      path: /suser/**
      serviceId: user-service