server:
  port: 6061
spring:
#  data:
#    elasticsearch:
#      cluster-name: elasticsearch
#      cluster-nodes: 192.168.0.193:9200
#      repositories:
#        enabled: true
  elasticsearch:
    rest:
      uris: http://192.168.0.193:9200
  redis:
    database: 1
    host: 192.168.0.193
#    password: 123456
    jedis:
      pool:
        max-active: 1024
        max-idle: 200
        max-wait: 10000
        min-idle: 0
    port: 6379
    timeout: 10000
  profiles:
    active: ${spring.cloud.config.profile}
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: goods-service
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.test.common.entity
  configuration:
    cache-enabled: false
    local-cache-scope: statement
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6060/eureka/
test:
  name: tom
  num: 20
#  instance:
#    instance-id: ${spring.cloud.client.hostname}:${spring.cloud.client.ipAddress}:${server.port}
#    prefer-ip-address: true
